### ISSUE TITLE
bug (state): Receipt requirement is counting old receipts

### ISSUE THREAD

**Issue by timoguin** [tiki/apps-receipt-capacitor#299]
# Current Behavior

After connecting Gmail and a retailer account, the receipt count requirement will be satisfied after the initial scans if there are at least 5 _past_ receipts discovered.

# Expected Behavior

The receipt requirement should only be satisfied after 5 _NEW_ receipts, not past receipts discovered during the initial scans.

**Comment by ricardobrg** [comment]
It happens because we are using the microblink's receipt id to check for duplicity, but it is unique for each scan, not throughout scans.

https://github.com/tiki/apps-receipt-capacitor/blob/b44a20ff19342c76996638ddcfe59025ba7dedda/src/service/store/state/state-receipt.ts#L30-L33

An option to avoid duplicity is to use a hash as unique id, composed by the merchant and date and time of the receipt.
