### ISSUE TITLE
[bug] Scroll problem in learn more page

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/apps-receipt-capacitor#315]
### Reason

The two last tables are disappearing from the screen

### Description

after insert the summary and collapsible content, the two last tables are disappearing from the screen if the user closes the summary

if remove the open attribute from the summary tag, the content its not rendered as well

### Success Criteria

- [ ] the screen should render all the content and it should not disappear when the user closes the summary

**Comment by timoguin** [comment]
@MiroBenicio this seems to be an issue with margins/padding at the bottom. I had originally added an additional horizontal rule to the bottom of the page (via `---` in the Markdown) because the text content was getting cut off.

You can see this behavior in the current screen where the text gets cut off at the bottom:

![Screenshot_20231017-130909](https://github.com/tiki/apps-receipt-capacitor/assets/671968/05ec8db9-b20a-4b8d-8c21-1bb04107480e)

Adding an additional horizontal rule after the last table fixes the issue with the last row being cut off, but it does not help with things disappearing with you collapse the details tag.

**Comment by ricardobrg** [comment]
@timoguin @MiroBenicio there are 2 issues here:

1 - The end of the text is cutoff: It is because the height of the learn more div is bigger than it should. The bottom sheet is 95vh the same side of the scroll container. When the scroll hits the bottom, there is still content to scroll. Changing full-screen height to 90vh solves the issue.

2 - The last summary content disappears: This is caused by nested details tags. The last details tag is rendered inside the last but one. The md file is correctly nested but when it is rendered by the md plugin it gets messed. We need to identify what in the md file is messing the html.

Another option is to change from the md file to the actual html. Is there any reason to not do that @timoguin ? I think it will not change so often, so you can build the table with md and @MiroBenicio converts to static html.

**Comment by ricardobrg** [comment]
The 1 was solved in #343. We changed the height of the viewport.

@MiroBenicio Let's try to solve 2 using a static html table. We will use the md to create the table and hardcode it in the component. After it is solved we can work on https://github.com/tiki/apps-receipt-capacitor/issues/344 as a definitive solution.
