### ISSUE TITLE
Compile API Documentation

### ISSUE THREAD

**Issue by sfaria27** [tiki/apps-receipt-capacitor#453]
As a team member, I need to compile documentation on the APIs involved in the CLO feature for the high-level system overview. This documentation will provide a comprehensive understanding of the external interfaces and integrations.

## Acceptance Criteria
- Identify all APIs integrated into the CLO feature.
- Document the purpose and functionalities of each API.
- Specify the communication protocols and data formats used by the APIs.
- Ensure the documentation is organized and easily accessible.
- Include any authentication mechanisms or security considerations associated with the APIs.

**Comment by ricardobrg** [comment]
# TIKI CLO API

This API facilitates Data Providers in linking cards, rewarding users for shopping with familiar brands. Users are automatically rewarded when using their cards at participating brands without the need for activation or acceptance of offers.

## Security in Transportation

The API exclusively supports secure connections through HTTPS. Ensure that API URLs start with `https://` instead of `http://` to encrypt data during transportation, adding an extra layer of security.

## Authentication

Access to the API requires a JWT token included in the request header. This token, containing information about the publisher and user, ensures secure and authorized access.

The JWT token serves two main purposes:

- **Authentication:** Validates the identity of the publisher and user, ensuring authorized API access.
  
- **Data Integrity:** The token's signature guarantees data integrity, preventing tampering during transportation. If the token is altered, the signature won't match, resulting in request rejection.

The JWT payload comprises:

- Publisher ID: A unique identifier for the publisher, provided by TIKI.
- User ID: A unique identifier for the user, provided by the publisher.

Example JWT token:
```plaintext
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI
```

## Add a Card to a User

To link a card to a user, no Personally Identifiable Information (PII) is required. The JWT sent with the request identifies both the user and publisher. Only card data is necessary:

### Request

#### Endpoint

- **Method:** `POST`
- **URL:** `/cards`

#### Request Body
```json
{
  "bin": 123456,
  "last4": 7890,
  "issuer": "Name_Of_Issuer",
  "network": "VISA"
}
```

#### Example Request

```bash
curl -X POST \
  https://api.example.com/cards \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI' \
  -H 'Content-Type: application/json' \
  -d '{
    "bin": 123456,
    "last4": 7890,
    "issuer": "Name_Of_Issuer",
    "network": "VISA"
  }'
```

### Response

On success, the response will be a 201 HTTP code with the card information.
```json
{
  "status": "success",
  "message": "Card linked successfully",
  "data": {
    "bin": 123456,
    "last4": 7890,
    "issuer": "Name_Of_Issuer",
    "network": "VISA"
  }
}
```

## Get User Cards

The `cards` endpoint returns a list of linked cards.

### Request

#### Endpoint

- **Method:** `GET`
- **URL:** `/cards`

#### Example Request

```bash
curl -X GET \
  https://api.example.com/cards \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI'
```

### Response

```json
{
  "status": "success",
  "data": [
    {
      "bin": 123456,
      "last4": 7890,
      "issuer": "Name_Of_Issuer",
      "network": "VISA"
    },
    {
      "bin": 987654,
      "last4": 4321,
      "issuer": "Another_Issuer",
      "network": "MASTERCARD"
    }
  ]
}
```

## Get User Offers

The `offers` endpoint returns a list of available offers for the user. Users don't need to activate offers; using a linked card at a participating brand automatically matches the transaction and rewards the user.

### Request

#### Endpoint

- **Method:** `GET`
- **URL:** `/offers`

#### Example Request

```bash
curl -X GET \
  https://api.example.com/offers \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4

mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI'
```

### Response

```json
{
  "status": "success",
  "data": [
    {
      "offerId": "offer-123",
      "merchant": "Some Merchant",
      "description": "10% cashback on purchases",
      "expiryDate": "2024-12-31"
    },
    {
      "offerId": "offer-456",
      "merchant": "Another Merchant",
      "description": "Free gift with every purchase",
      "expiryDate": "2024-11-30"
    }
  ]
}
```

## Send a Transaction

Data providers must send transactions to be matched with CLOs.

### Request

#### Endpoint

- **Method:** `POST`
- **URL:** `/transaction`

#### Example Request

```bash
curl -X POST \
  https://api.example.com/transaction \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI' \
  -H 'Content-Type: application/json' \
  -d '{
    "transactionId": "txn-789",
    "amount": 1500,
    "currency": "USD",
    "status": "APPROVED",
    "description": "Purchase at Some Merchant",
    "merchantId": "some-merchant-id",
    "cardBIN": 123456,
    "cardLastFour": 7890
  }'
```

### Response

```json
{
  "status": "success",
  "message": "Transaction matched successfully",
  "data": {
    "reward": {
      "merchantId": "some-merchant-id",
      "name": "Some Merchant",
      "type": "CARDLINKED",
      "status": "APPROVED",
      "commissionToIssuer": 100
    },
    "card": {
      "bin": 987654,
      "last4": 4321,
      "issuer": "Another_Issuer",
      "network": "MASTERCARD"
    },
    "transaction": {
      "issuerTransactionId": "txn-789",
      "transactionAmountInCents": 1500,
      "status": "APPROVED",
      "transactionTimeStamp": "2024-01-09T12:34:56.000+00:00"
    }
  }
}
```

## Get User Rewards

Retrieve current user rewards.

### Request

The user is identified by the JWT token.

#### Endpoint

- **Method:** `GET`
- **URL:** `/rewards`

#### Example Request

```bash
curl -X GET \
  https://api.example.com/rewards \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaXNoZXJJZCI6IjEyMzQ1Njc4OTAiLCJ1c2VySWQiOiJKb2huRG9lIn0.72o2BM9H4mzMKWReMP6xDJo59n0Ty_CBmqKRTX9BPBI'
```

### Response

Returns the list of rewards the user received from CLOs and the user's current balance.
```json
{
  "balance": 3.00,
  "rewards": [
    {
      "merchantId": "first-merchant-id",
      "name": "First Merchant",
      "transactionAmount": 500,
      "rewardAmount": 50,
      "card": {
        "bin": "987654",
        "last4": "4321",
        "network": "DISCOVER"
      }
    },
    {
      "merchantId": "first-merchant-id",
      "name": "First Merchant",
      "transactionAmount": 1500,
      "rewardAmount": 150,
      "card": {
        "bin": "987654",
        "last4": "4321",
        "network": "DISCOVER"
      }
    },
    {
      "merchantId": "second-merchant-id",
      "name": "Second Merchant",
      "transactionAmount": 2500,
      "rewardAmount": 100,
      "card": {
        "bin": "987654",
        "last4": "4321",
        "network": "DISCOVER"
      }
    }
  ]
}
```
